import type { Product, CustomSection, AppConfig, MediaItem } from "@/lib/schemas";

// ============================================================
// Seed Data — Diginast (High Performance Tech & Hardware)
// Categorías: Gaming, Workstations, Laptops, Componentes, Monitores, Audio Pro
// ============================================================

export const diginastSeed = {
  products: [
    {
      id: "dgn-gaming-xtreme-4090",
      foto: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=1200&h=800&fit=crop",
      titulo: "Setup Gaming Xtreme RTX 4090",
      tituloEn: "Gaming Setup Xtreme RTX 4090",
      caracteristicas: [
        "NVIDIA RTX 4090 24GB GDDR6X",
        "Intel Core i9-14900K 24 núcleos",
        "64GB RAM DDR5 6000MHz RGB",
        "2TB SSD NVMe PCIe 4.0",
        "Refrigeración Líquida 360mm ARGB",
      ],
      caracteristicasEn: [
        "NVIDIA RTX 4090 24GB GDDR6X",
        "Intel Core i9-14900K 24-core",
        "64GB DDR5 6000MHz RGB RAM",
        "2TB NVMe PCIe 4.0 SSD",
        "360mm ARGB Liquid Cooling",
      ],
      descripcion: "El setup gaming y estación de render definitivo. Equipado con la tarjeta gráfica más potente del mundo y procesador de 24 núcleos refrigerado por líquido. Máximo rendimiento para 4K/8K, streaming y renderizado pesado.",
      descripcionEn: "The ultimate gaming and rendering rig. Powered by the world's fastest GPU and a 24-core liquid-cooled CPU. Maximum throughput for 4K/8K gaming, streaming, and heavy 3D rendering workloads.",
      precio: 3499.00,
      oldPrice: 3899.00,
      tag: "Destacado",
      tagEn: "Featured",
      featured: true,
      category: "Gaming",
      categoryEn: "Gaming",
      inStock: true,
      stockCount: 5,
      videoUrl: "https://cdn.pixabay.com/video/2024/02/15/200946-916984661_large.mp4",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "dgn-workstation-creator-pro",
      foto: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=1200&h=800&fit=crop",
      titulo: "Workstation Creator Pro Threadripper",
      tituloEn: "Creator Pro Threadripper Workstation",
      caracteristicas: [
        "AMD Ryzen Threadripper 7970X 32C/64T",
        "Dual RTX 4090 48GB VRAM combinada",
        "128GB RAM DDR5 ECC Quad-Channel",
        "8TB SSD NVMe Raid 0",
        "Fuente 1600W Titanium 80+",
      ],
      caracteristicasEn: [
        "AMD Ryzen Threadripper 7970X 32C/64T",
        "Dual RTX 4090 48GB combined VRAM",
        "128GB DDR5 ECC Quad-Channel RAM",
        "8TB NVMe SSD RAID 0",
        "1600W Titanium 80+ PSU",
      ],
      descripcion: "Diseñada para arquitectos, científicos de datos, cineastas y desarrolladores de IA. Potencia computacional sin límites para compilar código masivo, entrenar modelos locales y renderizar 8K en tiempo real.",
      descripcionEn: "Engineered for architects, AI data scientists, film directors, and developers. Limitless compute power to compile large-scale codebases, train local models, and render 8K footage in real time.",
      precio: 5899.00,
      oldPrice: null,
      tag: "Nuevo",
      tagEn: "New",
      featured: true,
      category: "Workstations",
      categoryEn: "Workstations",
      inStock: true,
      stockCount: 3,
      videoUrl: "https://cdn.pixabay.com/video/2022/12/12/142466-780669638_large.mp4",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "dgn-laptop-ultra-creator-16",
      foto: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&h=800&fit=crop",
      titulo: "Laptop Ultra Creator 16\" OLED 4K",
      tituloEn: "Ultra Creator 16\" 4K OLED Laptop",
      caracteristicas: [
        "Pantalla 16\" OLED 4K 120Hz 100% DCI-P3",
        "Intel Core Ultra 9 185H",
        "NVIDIA RTX 4080 12GB GDDR6",
        "64GB RAM LPDDR5X 7467MHz",
        "Chasis CNC de Magnesio y Aluminio",
      ],
      caracteristicasEn: [
        "16\" 4K 120Hz 100% DCI-P3 OLED Display",
        "Intel Core Ultra 9 185H",
        "NVIDIA RTX 4080 12GB GDDR6",
        "64GB LPDDR5X 7467MHz RAM",
        "Magnesium-Aluminum CNC Chassis",
      ],
      descripcion: "La estación de trabajo portátil más elegante y poderosa. Panel OLED calibrado de fábrica para colorimetría perfecta, batería de 99Wh y conectividad Thunderbolt 4 dual.",
      descripcionEn: "The most elegant and powerful portable workstation. Factory-calibrated OLED display for true-to-life colors, 99Wh battery life, and dual Thunderbolt 4 connectivity.",
      precio: 2299.00,
      oldPrice: 2499.00,
      tag: "Oferta",
      tagEn: "Sale",
      featured: true,
      category: "Laptops",
      categoryEn: "Laptops",
      inStock: true,
      stockCount: 8,
      videoUrl: null,
      updatedAt: new Date().toISOString(),
    },
    {
      id: "dgn-gpu-rtx-4090-oc",
      foto: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=1200&h=800&fit=crop",
      titulo: "GPU NVIDIA GeForce RTX 4090 OC 24GB",
      tituloEn: "NVIDIA GeForce RTX 4090 OC 24GB GPU",
      caracteristicas: [
        "24GB GDDR6X 384-bit",
        "Arquitectura Ada Lovelace 4nm",
        "DLSS 3.5 con Frame Generation",
        "Disipador Vapor Chamber triple ventilador",
        "Backplate reforzado con RGB direccionable",
      ],
      caracteristicasEn: [
        "24GB GDDR6X 384-bit",
        "Ada Lovelace 4nm Architecture",
        "DLSS 3.5 with Frame Generation",
        "Triple-Fan Vapor Chamber Cooler",
        "Reinforced Backplate with Addressable RGB",
      ],
      descripcion: "Tarjeta gráfica tope de gama para gaming competitivo, modelado 3D, Ray Tracing completo y aceleración por hardware con núcleos Tensor de 4ta generación.",
      descripcionEn: "Top-of-the-line graphics card for competitive gaming, 3D modeling, full path-traced ray tracing, and 4th Gen Tensor Core hardware acceleration.",
      precio: 1599.00,
      oldPrice: 1750.00,
      tag: "Popular",
      tagEn: "Popular",
      featured: true,
      category: "Componentes",
      categoryEn: "Components",
      inStock: true,
      stockCount: 12,
      videoUrl: null,
      updatedAt: new Date().toISOString(),
    },
    {
      id: "dgn-monitor-odyssey-neo-g9",
      foto: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=1200&h=800&fit=crop",
      titulo: "Monitor Curvo 57\" Dual UHD 240Hz",
      tituloEn: "57\" Dual UHD 240Hz Curved Monitor",
      caracteristicas: [
        "Resolución Dual UHD 7680x2160 (32:9)",
        "Tasa de refresco 240Hz con 1ms GtG",
        "Tecnología Quantum Mini-LED HDR2000",
        "Curvatura inmersiva 1000R",
        "DisplayPort 2.1 y HDMI 2.1",
      ],
      caracteristicasEn: [
        "Dual UHD 7680x2160 Resolution (32:9)",
        "240Hz Refresh Rate with 1ms GtG",
        "Quantum Mini-LED HDR2000 Tech",
        "1000R Immersive Curvature",
        "DisplayPort 2.1 & HDMI 2.1",
      ],
      descripcion: "El monitor panorámico más avanzado jamás creado. Equivalente a dos pantallas 4K lado a lado sin biseles. Ideal para multitarea masiva, simuladores y visualización inmersiva.",
      descripcionEn: "The most advanced ultrawide monitor ever created. Equivalent to dual 4K screens seamlessly joined without bezels. Perfect for massive multitasking, flight sims, and immersive gaming.",
      precio: 1899.00,
      oldPrice: 2199.00,
      tag: "Oferta",
      tagEn: "Sale",
      featured: true,
      category: "Monitores",
      categoryEn: "Monitors",
      inStock: true,
      stockCount: 4,
      videoUrl: null,
      updatedAt: new Date().toISOString(),
    },
    {
      id: "dgn-audio-studio-pro",
      foto: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1200&h=800&fit=crop",
      titulo: "Setup Audio Pro Studio & Stream",
      tituloEn: "Studio & Stream Audio Pro Setup",
      caracteristicas: [
        "Monitores de Estudio Bi-amplificados 8\"",
        "Interfaz de Audio USB-C 24-bit/192kHz",
        "Micrófono Dinámico de Broadcast XLR",
        "Brazo articulado de perfil bajo con cableado oculto",
        "DSP integrado con limitador y ecualizador",
      ],
      caracteristicasEn: [
        "8\" Bi-amplified Studio Reference Monitors",
        "24-bit/192kHz USB-C Audio Interface",
        "Broadcast XLR Dynamic Microphone",
        "Low-profile Boom Arm with hidden cable run",
        "Integrated DSP with limiter and EQ",
      ],
      descripcion: "Kit completo de audio profesional para podcasters, músicos y streamers. Respuesta plana de frecuencia cristalina y preamplificadores de ruido ultra bajo.",
      descripcionEn: "Complete pro-audio package for podcasters, sound designers, and streamers. Crystal-clear flat frequency response and ultra-low noise preamps.",
      precio: 899.00,
      oldPrice: 999.00,
      tag: "Kit",
      tagEn: "Bundle",
      featured: false,
      category: "Audio Pro",
      categoryEn: "Audio Pro",
      inStock: true,
      stockCount: 15,
      videoUrl: null,
      updatedAt: new Date().toISOString(),
    },
  ] as Product[],

  sections: [
    {
      id: "sec-featured",
      title: "Setups y Equipos Más Solicitados",
      background: null,
      position: "below" as const,
      productIds: ["dgn-gaming-xtreme-4090", "dgn-workstation-creator-pro", "dgn-gpu-rtx-4090-oc"],
      active: true,
      order: 0,
      accentColor: null,
      overlayOpacity: 0.55,
      titleColor: null,
      autoComplementary: true,
      buttonColor: null,
    },
  ] as CustomSection[],

  config: {
    brandName: "Diginast",
    pageTitle: "Diginast — Tecnología de Vanguardia & Hardware Pro",
    heroTitle: "Potencia que inspira",
    heroSubtitle: "Descubre el futuro de la tecnología con setups y equipos de alto rendimiento para gaming, ingeniería y producción.",
    heroBackgroundUrl: "",
    whatsapp: {
      phone: "584127670871",
    },
    buttons: {
      main: {
        label: "Solicitar Cotización",
        action: "whatsapp-info",
        href: "",
        variant: "solid-primary",
        visible: true,
        whatsappTemplate: "Hola Diginast, me gustaría cotizar un equipo personalizado.",
      },
      order: {
        label: "Cotizar por WhatsApp",
        action: "whatsapp-order",
        href: "",
        variant: "solid-accent",
        visible: true,
        whatsappTemplate: "Hola Diginast, quiero cotizar el siguiente producto: ",
      },
      back: {
        label: "Volver",
        action: "back",
        href: "",
        variant: "ghost",
        visible: true,
        whatsappTemplate: "",
      },
    },
    categories: [
      { id: "gaming", name: "Gaming", imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=800&fit=crop", order: 0 },
      { id: "workstation", name: "Workstations", imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=600&h=800&fit=crop", order: 1 },
      { id: "laptops", name: "Laptops", imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=800&fit=crop", order: 2 },
      { id: "componentes", name: "Componentes", imageUrl: "https://images.unsplash.com/photo-1591488320449-011701bb6704?w=600&h=800&fit=crop", order: 3 },
      { id: "monitores", name: "Monitores", imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&h=800&fit=crop", order: 4 },
      { id: "audio", name: "Audio Pro", imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=800&fit=crop", order: 5 },
    ],
    promos: {
      flashVisible: true,
      flashBtnLabel: "Ver Ofertas",
      specialVisible: true,
      specialBtnLabel: "Saber Más",
      specialBg: null,
    },
    featuredSection: {
      title: "Productos Premium",
      background: null,
      accentColor: null,
      overlayOpacity: 0.55,
      titleColor: null,
      buttonColor: null,
      autoComplementary: true,
      order: 50,
      visible: true,
    },
  } as AppConfig,

  media: [] as MediaItem[],
};

export type DiginastSeed = typeof diginastSeed;
